# cpp_core.pyi
# Static type stubs for the compiled pybind11 C++ module

class StrategyUpdate:
    spread_bps: float
    skew_bps: float
    regime_id: int
    def __init__(self, spread_bps: float, skew_bps: float, regime_id: int) -> None: ...

class SPSCQueue:
    def __init__(self, capacity: int) -> None: ...
    def push(self, update: StrategyUpdate) -> bool: ...
    def pop(self) -> StrategyUpdate | None: ...

class LOBEngine:
    def __init__(self, queue: SPSCQueue, max_pos: float, max_spread: float) -> None: ...
    def on_market_tick(self, mid_price: float) -> None: ...
